### ISSUE TITLE
[Bug] `BlockScanner.next()`occasionally results in `connection closed before message completed`

### ISSUE THREAD

**Issue by 0xKitsune** [worldcoin/world-tree#104]
### Describe the bug

`BlockScanner.next()` results in `connection closed before message completed` which can cause updates to be missed from the canonical or bridged trees. This can cause the service to crash if a log is missed from the canonical tree but consumed for bridged trees, resulting in errors stating `Could not get root update`.

```
INFO world_tree::tree::tree_manager: src/tree/tree_manager.rs:179: Root updated, chain_id: 10, new_root: 18038768551743628277444722133465440576400028068694469689241733847525215915401

INFO world_tree::tree: src/tree/mod.rs:231: Bridged root received, chain_id: 10, root: 18038768551743628277444722133465440576400028068694469689241733847525215915401

thread 'tokio-runtime-worker' panicked at world-tree/src/tree/mod.rs:238:22:
Could not get root update
```

**Comment by Dzejkop** [comment]
We now have a restart mechanism over each internal task, so the spurious connection lost should not be an issue
